/*
проверка состояний по стайлгайду
ищем элементы по текстовому содержанию
 */

module.exports = {
  "id": "sedona test-07",
  "viewports": [
    {
      "label": "desktop",
      "width": 1280,
      "height": 800,
    },
  ],
  "onReadyScript": "onReady.js",
  "scenarios": [
    {
      "label": "index TEST-07. Normal 1",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".search-button"],
      content: "Поиск гостиницы в Седоне",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Hover 1",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".search-button"],
      content: "Поиск гостиницы в Седоне",
      hoverSelector: ".search-button",
      onReadyScript: "interaction.js",
      // fixme не работает ховер на этой кнопке в референсе
      postInteractionWait: 300,
    },
    {
      "label": "index TEST-07. Active 1",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".search-button"],
      content: "Поиск гостиницы в Седоне",
      activeSelector: ".search-button",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Focus 1",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".search-button"],
      content: "Поиск гостиницы в Седоне",
      focusSelector: ".search-button",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Disable 1",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".search-button"],
      content: "Поиск гостиницы в Седоне",
      disableSelector: ".search-button",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Normal 2",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".subscribe-button"],
      content: "Подписаться",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Hover 2",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".subscribe-button"],
      content: "Подписаться",
      hoverSelector: ".subscribe-button",
      onReadyScript: "interaction.js",
      // fixme не работает ховер на этой кнопке в референсе
      postInteractionWait: 300,
    },
    {
      "label": "index TEST-07. Active 2",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".subscribe-button"],
      content: "Подписаться",
      activeSelector: ".subscribe-button",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Focus 2",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".subscribe-button"],
      content: "Подписаться",
      focusSelector: ".subscribe-button",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Disable 2",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".subscribe-button"],
      content: "Подписаться",
      disableSelector: ".subscribe-button",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Normal 3",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".footer-phone"],
      content: "+7 (812) 812-12-12",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Hover 3",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".footer-phone"],
      content: "+7 (812) 812-12-12",
      hoverSelector: ".footer-phone",
      onReadyScript: "interaction.js",
      postInteractionWait: 300,
    },
    {
      "label": "index TEST-07. Active 3",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".footer-phone"],
      content: "+7 (812) 812-12-12",
      activeSelector: ".footer-phone",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Focus 3",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".footer-phone"],
      content: "+7 (812) 812-12-12",
      focusSelector: ".footer-phone",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Disable 3",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: [".footer-phone"],
      content: "+7 (812) 812-12-12",
      disableSelector: ".footer-phone",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Normal 4",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: ["a[href*=\"htmlacademy\.ru\"]"],
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Hover 4",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: ["a[href*=\"htmlacademy\.ru\"]"],
      hoverSelector: "a[href*=\"htmlacademy\.ru\"]",
      onReadyScript: "interaction.js",
      postInteractionWait: 300,
    },
    {
      "label": "index TEST-07. Active 4",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: ["a[href*=\"htmlacademy\.ru\"]"],
      activeSelector: "a[href*=\"htmlacademy\.ru\"]",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Focus 4",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: ["a[href*=\"htmlacademy\.ru\"]"],
      focusSelector: "a[href*=\"htmlacademy\.ru\"]",
      onReadyScript: "interaction.js",
    },
    {
      "label": "index TEST-07. Disable 4",
      "url": "./project/index.html",
      "referenceUrl": "./reference/index.html",
      selectors: ["a[href*=\"htmlacademy\.ru\"]"],
      disableSelector: "a[href*=\"htmlacademy\.ru\"]",
      onReadyScript: "interaction.js",
    },
    ...[
      { page: 'catalog', selector: '.header-button', content: 'Хочу сюда!' },
      { page: 'catalog', selector: '.control-label', content: 'Бассейн' },
      { page: 'catalog', selector: '.control-label', content: 'Гостиница' },
      { page: 'catalog', selector: '.catalog-filter-submit', content: 'Применить' },
      { page: 'catalog', selector: '.catalog-filter-reset', content: 'Сбросить' },
      { page: 'catalog', selector: '.breadcrumbs-link', content: 'Гостиницы', ancestor: '*[@data-test="main"]' },
      { page: 'catalog', selector: '.select-control', content: 'Сначала дешевые' },
      { page: 'catalog', selector: '.product-card-title', content: 'Amara Resort & Spa' },
      { page: 'catalog', selector: '.product-card-button', content: 'Подробнее' },
      { page: 'catalog', selector: '.add-favorite-button', content: 'В избранное' },
      { page: 'catalog', selector: '.pagination-link', content: '10' },
      // { page: 'catalog', selector: '[data-test="social"]' },
      // { page: 'catalog', selector: '[data-test="sort"]' },
      { page: 'modal', selector: '[data-test="modal"] button' },
    ].flatMap(({page, selector, content, ancestor }, idx) => ['normal', 'hover', 'active', 'focus', 'disable'].map(state => ({
        "label": `${page} TEST-07. ${state} ${idx}`,
        "url": `./project/${page}.html`,
        "referenceUrl": `./reference/${page}.html`,
        selectors: [selector],
        content,
        ancestor,
        [`${state}Selector`]: selector,
        onReadyScript: "interaction.js",
      })
    )),
  ],
  fileNameTemplate: '{configId}_{scenarioIndex}_{scenarioLabel}_{selectorIndex}__{viewportIndex}_{viewportLabel}',
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference/test-07",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "engine_scripts",
    "html_report": "backstop_data/html_report",
  },
  "report": ["browser"],
  "engine": "puppeteer",
  "engineOptions": {
    "args": ["--no-sandbox"],
    "gotoParameters": { "waitUntil": ["load", "networkidle0"], timeout: 10000 },
  },
  "asyncCaptureLimit": 10,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}
